# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FBBooking' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FBBooking
  pod 'SnapKit', '4.2.0'
  pod 'Kingfisher', '5.6.0'
  pod 'SwiftyJSON', '4.2.0'
  pod 'RxSwift','4.4.0'
  pod 'RxCocoa','4.4.0'
end
