# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FBBooking' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FBBooking
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'SwiftyJSON'
 pod 'RxSwift'
 pod 'RxCocoa'
 pod 'Pulley'
 pod 'CocoaLumberjack/Swift'
end
